### ISSUE TITLE
ocean.pangeo.io maintenance hack session

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-cloud-federation#622]
As discussed in #616 and https://discourse.pangeo.io/t/migration-of-ocean-pangeo-io-user-accounts/644/15, we will be doing maintenance on ocean.pangeo.io and other GCP clusters next week. @jhamman and I have blocked off **Monday, June 22, 2-5pm EDT** for a sprint on this. I invite everyone, and in particular @TomAugspurger, @scottyhq, @salvis2, @consideRatio, and @yuvipanda to help us out with this.

Some of the things we need to do are:

- [x] review the results of the account migration form and decide which user accounts will be migrated
- [x] write a script to migrate ORCID to github user IDs
- [x] delete non-migrated home directories
- [x] switch ocean.pangeo.io authentication to auth0
- [x] write documentation explaining deprecation of Dask Kubernetes and how to use Dask Gateway
- [x] set up some sort of logging (see #72) so we can better track usage statistics. Pinging @yuvipanda to get the latest on what is the best practice here
- [x] change image specification, building to use upstream pieces from pangeo-docker-images

What am I missing from this list?

**Comment by TomAugspurger** [comment]
I'll be around for most of the session, but will have to pop out for a couple calls.

**Comment by rabernat** [comment]
I'm looking forward to this hack session today.

**Comment by jhamman** [comment]
Let's jump in https://whereby.com/pangeo to kick things off.

**Comment by jhamman** [comment]
Some working notes here: https://hackmd.io/@U4W-olO3TX-hc-cvbjNe4A/r13p_PRaL/edit

**Comment by TomAugspurger** [comment]
For " write documentation explaining deprecation of Dask Kubernetes and how to use Dask Gateway" we can pull content from https://medium.com/pangeo/pangeo-with-dask-gateway-4b638825f105, specifically https://medium.com/pangeo/pangeo-with-dask-gateway-4b638825f105#af22 for explaining how to transition.

**Comment by TomAugspurger** [comment]
I can look into logging / monitoring things. Both jupyterhub and Dask expose prometheus metrics, and mybinder has details on capturing & visualizing them: https://mybinder-sre.readthedocs.io/en/latest/components/metrics.html

**Comment by rabernat** [comment]
> I can look into logging / monitoring things. Both jupyterhub and Dask expose prometheus metrics

That's awesome! What we would like most is to be able to run a query to find a how much time an individual user has accumulated over a given period on both jupyter and dask.

**Comment by jhamman** [comment]
My update from day 1:

- [x] Tear down of all three JupyterHub's in GCP
- [x] Reorg this repository to include a single GCP hub (renamed ocean to gcp-uscentral1b), see #625 
- [ ] Develop simple Makefile for standing up new k8s cluster that uses auto nodepool provisioning, see #625 

Still to do:

- [ ] sort out some details related to rbac/service accounts in #625
- [ ] test deployment of pangeo helm chart
- [ ] update hubploy / circleci configs

**Comment by scottyhq** [comment]
> update hubploy / circleci configs 

This will be useful for just pointing to existing images on DockerHub
https://github.com/yuvipanda/hubploy/pull/75 

Or if images continue to be built in this repo, it makes sense to put them on DockerHub rather than aws or gcp registries which are harder for people to get to. So could revisit https://github.com/yuvipanda/hubploy/pull/24

**Comment by rabernat** [comment]
The account migration is in progress. Those with credentials can see the backed up homedirs here: https://console.cloud.google.com/storage/browser/pangeo-homedir-backup

There is a long tail of very large home directories on ocean that will take a very long time to complete.

**Comment by rabernat** [comment]
For reference, the backup scripts are here: https://gist.github.com/rabernat/c9b352de926756342e86da662a0eadf9

**Comment by TomAugspurger** [comment]
> Or if images continue to be built in this repo, it makes sense to put them on DockerHub rather than aws or gcp registries which are harder for people to get to.

I think we're hoping to still upload to GCP / AWS to keep the startup times as small as possible when an image does need to be downloaded.

**Comment by salvis2** [comment]
Today I'll work on standing up a test cluster and testing that Linux hack to enforce user storage limits.

**Comment by scottyhq** [comment]
@salvis2 @rabernat - before you dive into the storage limits, do you have a solution for dealing with the fact that every user has the same uid and gid (1000,1000)? This has come up a few times before https://github.com/pangeo-data/pangeo-cloud-federation/issues/384#issuecomment-526401660 https://github.com/pangeo-data/pangeo-cloud-federation/issues/25

**Comment by rabernat** [comment]
My idea was to try to do the quota-ing from within the user's jupyter pod. Basically, this pod is a unix system with one user--jovyan (1000,1000)--whose home directory is mounted from an nfs server.

Is is possible to make this unix instance enforce a quota on that one user? It doesn't have to know about all the other users or address the challenge of duplicated uid / gid. It just has to prevent jovyan from creating more than 10GB of files in /home/jovyan.

Seems like it should be possible to me, but I have likely overlooked something.

**Comment by scottyhq** [comment]
ok. definitely sounds like something worth exploring! 

One more idea/request on the topic of "update hubploy / circleci configs". I think it would be great to drop circleci in favor of github actions. Hubploy now works with github actions (for example https://github.com/ICESAT-2HackWeek/jupyterhub-2020). And we could make use of organization level secrets to reduce scattering in various places. https://github.blog/changelog/2020-05-14-organization-secrets/.

**Comment by rabernat** [comment]
> I think it would be great to drop circleci in favor of github actions. Hubploy now works with github actions

💯 x 👍

**Comment by rabernat** [comment]
Home directory backup is complete. Should I just `rm -rf *` the NFS volume?

**Comment by jhamman** [comment]
>Should I just rm -rf * the NFS volume?

@rabernat - let's leave it for a few days. I actually think we'll want to create a new (smaller) nfs service so we may just remove the existing one all together.

**Comment by rabernat** [comment]
@jhamman -- let me know when you're ready for me to transfer the migrated ocean.pangeo.io users to the new NFS server.

**Comment by rabernat** [comment]
What's the status today? Are we ready to starting bringing up the new cluster?

For DNS, I suggest we go with the region-based names, i.e. `us-central-1b.gcp.pangeo.io`.

**Comment by jhamman** [comment]
Update...

@TomAugspurger and I have been working on standing up the new hub. This is going well and we should be ready for the user home directories now at the following NFS location:

```
10.126.142.50:/home/uscentral1b/{GITHUB_USER}
```

@rabernat - we're also ready to configure Auth0 and the DNS record. I can't do this because my access to the Pangeo Auth0 account is still broken.

The branch to work off right now is: https://github.com/pangeo-data/pangeo-cloud-federation/pull/626

**Comment by salvis2** [comment]
Do the GCP clusters use NFS Provisioner for making new user home directories? There is a way to run the binary apparently that can enforce user quotas: https://github.com/kubernetes-incubator/external-storage/blob/master/nfs/docs/deployment.md#outside-of-kubernetes---binary

This doesn't appear to be an option in [NFS-Client Provisioner](https://github.com/helm/charts/tree/master/stable/nfs-client-provisioner). I'm a little fuzzy on the distinction between the two, but the first link is the only thing I could find on quotas. Linux hacking has yet to yield anything useful.

**Comment by rabernat** [comment]
> Do the GCP clusters use NFS Provisioner for making new user home directories

I'm not sure. All I know is that they use NFS for home directories. The chart is in #262 

> we should be ready for the user home directories now at the following NFS location:

On it.

> we're also ready to configure Auth0 and the DNS record

Do we have an IP address for the DNS record?

**Comment by rabernat** [comment]
I have hit a challenge with the NFS server permissions, described in #627. Any ideas would be appreciated.

**Comment by rabernat** [comment]
Home directories are now (or will soon be) working.

**Comment by TomAugspurger** [comment]
The dask side of things is up now.

I'm not familiar with how we did DNS before. Do we need to reserve some address in GCP? RIght now the hub's IP is 34.69.173.244.

**Comment by TomAugspurger** [comment]
Telemetry stuff seems to work at a glance. We'll need to talk about what if anything should be public.

If you want to mess with grafana the steps currently are

```
cd deployments/gcp-uscentral1b
# get the password
# remove the | pbcopy if you aren't on a Mac
make print-grafana-password | pbcopy
# tunnel into the grafana server
make forward-grafana
```

Then login with username: `admin` and the password that should be on your clipboard. I think we'll eventually hook grafana up to some auth system like GitHub.

**Comment by rabernat** [comment]
> I'm not familiar with how we did DNS before. Do we need to reserve some address in GCP? RIght now the hub's IP is 34.69.173.244.

There is some way to convert this to a permanent IP address.

**Comment by TomAugspurger** [comment]
Thanks, done. It's named  `gcp-uscentral1b`.

**Comment by rabernat** [comment]
Yikes, I just tried doing it at the same time. I got an error "The request contains invalid arguments: "Invalid value for field 'resource.address': '34.69.173.244'. Specified IP address is already reserved.". Error code: "invalid""

**Comment by rabernat** [comment]
We also have to add this IP to the chart somewhere.

**Comment by rabernat** [comment]
I'll work on DNS.

**Comment by TomAugspurger** [comment]
Thanks, sorry for the duplicate work there. Added the stable IP to the chart in https://github.com/pangeo-data/pangeo-cloud-federation/pull/628.

**Comment by rabernat** [comment]
This is what I see now on https://console.cloud.google.com/networking/addresses/list?project=pangeo-181919

![image](https://user-images.githubusercontent.com/1197350/85887959-afd31a80-b7b6-11ea-8bfa-b52357b133bd.png)

Looks like a created a problem.

**Comment by TomAugspurger** [comment]
Hmm I don't see any issues.

![Screen Shot 2020-06-26 at 1 12 07 PM](https://user-images.githubusercontent.com/1312546/85888172-aba2ff00-b7ae-11ea-8969-498c4fbfa4f9.png)

**Comment by rabernat** [comment]
I'm stumped on some conceptual things for auth0. If anyone wants to hop into https://whereby.com/pangeo for a chat, I'd love to bounce some ideas around.

**Comment by rabernat** [comment]
Also, DNS is up (http://staging.us-central1-b.gcp.pangeo.io/) but https is not yet configured. Does anyone know how to do this?

**Comment by TomAugspurger** [comment]
HTTPs may just be a matter of uncommenting
https://github.com/pangeo-data/pangeo-cloud-federation/blob/0c33675fa235fdf4a9c88f8daf6ec00ee01d22ad/deployments/gcp-uscentral1b/config/staging.yaml#L4-L8?
Maybe updating the email?

**Comment by salvis2** [comment]
I believe you are supposed to first get the hub up-and-running without HTTPS, do some DNS pointing, _then_ enable HTTPS. https://zero-to-jupyterhub.readthedocs.io/en/latest/administrator/security.html#https

It looks like prod had the HTTPS block always enabled: https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/gcp-uscentral1b/config/prod.yaml#L5-L8

**Comment by consideRatio** [comment]
If HTTPS doesnt configure itself properly, I know that it could be needed to delete a secret named something like hub-proxy-tls and then delete the autohttps pod.

**Comment by jhamman** [comment]
My update from today:

### staging

https://staging.us-central1-b.gcp.pangeo.io/ is now live and is using [Pangeo's Auth0](https://pangeo.auth0.com/) account. 

For the staging hub, the main thing to sort out is the  dask gateway service. @rabernat and I were getting  the following error when we took the hub for a test drive:

```
ClientResponseError: 503, message='Service Unavailable', url=URL('https://staging.us-central1-b.gcp.pangeo.io/services/dask-gateway/api/v1/clusters/')
```

### prod

I added the config for https://us-central1-b.gcp.pangeo.io/ to the `staging` branch but I didn't manage to get it deployed. Currently running into an issue with lingering k8s resources:

```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: , name: us-central1b-prod-grafana, existing_kind: policy/v1beta1, Kind=PodSecurityPolicy, new_kind: policy/v1beta1, Kind=PodSecurityPolicy
```

@TomAugspurger - this looks familiar to what we saw yesterday, no?

**Comment by TomAugspurger** [comment]
I thought I fixed the 503 error for gateway. Can you make sure you pulled staging before helm deploying?

**Comment by TomAugspurger** [comment]
I redeployed from staging. Things seem to be OK.

Not sure about prod right now.

**Comment by rabernat** [comment]
Summary from some discussion with @jhamman yesterday.

We want to find the simplest way to exercise more control over user privileges across our clusters. I thought about it and think the following could work:
- All users have to fill out a google form which populates a spreadsheet
- We configure the form to an email to a list of admins
- There is an extra column for each cluster (e.g. `us-central1-b`) which us admins manually check to approve the user
- We create a very simple API to query this spreadsheet (could even run in the same heroku account as [pangeo-gallery-bot](https://github.com/pangeo-gallery/pangeo-gallery-bot))
- We call this API in an Auth0 rule, as described in [this example](https://auth0.com/docs/users/references/user-data-storage-scenario) and assign users an appropriate auth0 role based on the response
- We have another rule that matches roles to cluster login rights

I think we can make this work. I can create the API if @scottyhq can create the rules.

**Comment by rabernat** [comment]
Is there a public endpoint for the grafana dashboards?

**Comment by salvis2** [comment]
> Is there a public endpoint for the grafana dashboards?

Grafana should have an External-IP / service. I know you can put a DNS address to point to it but I'm still fuzzy on doing HTTPS with it through JupyterHub. @consideRatio could probably speak to that more if you are curious.

You can [enable anonymous logins for Grafana](https://grafana.com/docs/grafana/latest/auth/overview/#anonymous-authentication) and configure what anonymous users are able to see via settings on their [organization role](https://grafana.com/docs/grafana/latest/permissions/organization_roles/#organization-roles).

**Comment by rabernat** [comment]
Ah ok I I just figured out how to see grafana locally (actually read @TomAugspurger's comment in . https://github.com/pangeo-data/pangeo-cloud-federation/issues/622#issuecomment-650311119).

I can now see a basic Grafana interface, but it doesn't have any dashboards and I don't know how to create one. Is there an issue to discuss that?

**Comment by TomAugspurger** [comment]
No public dashboard yet. We’ll need to decide if there’s anything that shouldn’t be public.

Right now the dashboards seem to be lost on each helm deploy. Haven’t figured out how to persist them yet.

**Comment by salvis2** [comment]
I think you need to build the dashboards into the Helm release. It's not super clear, but this seems to be somewhere to start: https://github.com/helm/charts/tree/master/stable/grafana#import-dashboards

**Comment by jhamman** [comment]
https://us-central1-b.gcp.pangeo.io is now up

> No public dashboard yet. We’ll need to decide if there’s anything that shouldn’t be public.

@consideRatio - do you know if it is possible (or what it would take) to put grafana behind the admin permissions of a jupyterhub service?

**Comment by rabernat** [comment]
Tomorrow morning I plan to send an email to the users of the new cluster to let them know it's on.

**Comment by TomAugspurger** [comment]
@jhamman do you know what's left to do for getting things hooked up to hubploy?

**Comment by jhamman** [comment]
I think we just need to:

- uncomment the various pieces of the circleci config, e.g. https://github.com/pangeo-data/pangeo-cloud-federation/blob/461606efb8b64af97d6d45a295d4e9b06e7bcaf4/.circleci/config.yml#L177-L182
- repopulate the gcloud service key: https://github.com/pangeo-data/pangeo-cloud-federation/blob/staging/deployments/gcp-uscentral1b/secrets/gcloud-service-key.json

**Comment by rabernat** [comment]
I'm about to push a big update to pangeo.io with documentation about the new setup.

**Comment by jhamman** [comment]
@TomAugspurger - any idea what is up with these _Pending_ pods:

```
$ kubectl get pod -n prod | grep Pending
us-central1b-prod-prometheus-node-exporter-2n97g                  0/1     Pending   0          42h
us-central1b-prod-prometheus-node-exporter-dw689                  0/1     Pending   0          42h
us-central1b-prod-prometheus-node-exporter-j42ms                  0/1     Pending   0          42h
us-central1b-prod-prometheus-node-exporter-wnsjv                  0/1     Pending   0          42h
```

**Comment by TomAugspurger** [comment]
Not sure. Probably safe to just delete?

**Comment by jhamman** [comment]
> Not sure. Probably safe to just delete?

tried that. they just come back in the same state.

**Comment by rabernat** [comment]
See https://github.com/pangeo-data/pangeo/pull/780 for documentation update. I'd appreciate a review there.

**Comment by rabernat** [comment]
Another question: the dask widget is still set up to launch kubeclusters. I think we should not allow kubecluster on the new cluster. So what do we do about the widget? Can we make it launch dask_gateway clusters?

**Comment by TomAugspurger** [comment]
I believe that's coming from the `dask_config.yaml` that's baked into the docker images at https://github.com/pangeo-data/pangeo-docker-images/blob/6ba7997b5246440c0f1b92512cb133b98c6b976d/base-image/dask_config.yml#L58-L63. Just switching that to dask-gateway won't work out of the box since the labextension is only set up to create a cluster like `class(*args, **kwargs)`. But dask-gateway needs to create the intermediate `Gateway` object.

**Comment by rabernat** [comment]
> But dask-gateway needs to create the intermediate `Gateway` object.

So we need to open an issue in dask-labextension?

**Comment by TomAugspurger** [comment]
Opened https://github.com/dask/dask-labextension/issues/135

**Comment by rabernat** [comment]
Thanks for your work everyone! The new cluster is launched.

Whenever you get time @TomAugspurger, I would love if you could explain to me how to use grafana / prometheus to gather the information I need about usage.

**Comment by alimanfoo** [comment]
Hi pangeo folks, apologies for stalking but found this issue while googling for whether there was some way to configure storage quotas when using NFS on GCP. If anyone found a solution to that I'd be very grateful for a pointer.
